import { StyleSheet } from "react-native";
export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  passwordResetBtn: {
    backgroundColor: "#34495e",
    borderRadius: 10,
    width: 200,
    marginVertical: 20,
    alignItems: "center",
    elevation: 3,
    shadowOffset: { width: 2, height: 2 },
    shadowColor: "#333",
    shadowOpacity: 0.4,
    shadowRadius: 2,
  },
  disabledPWResetBtn: {
    backgroundColor: "#bdc3c7",
    borderRadius: 10,
    borderColor: "#34495e",
    borderWidth: 1,
    width: 200,
    marginVertical: 20,
    alignItems: "center",
    justifyContent: "center",
    elevation: 3,
    shadowOffset: { width: 2, height: 2 },
    shadowColor: "#333",
    shadowOpacity: 0.4,
    shadowRadius: 2,
  },
  textInput: {
    borderBottomWidth: 1,
    width: "50%",
    height: 30,
    fontSize: 20,
    padding: 5,
  },
  headerTextView: { justifyContent: "center", alignSelf: "center" },
  headerText: { fontSize: 32, fontWeight: "700", textAlign: "center" },
  inputView: {
    width: "90%",
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 10,
  },
  fontSize: { fontSize: 18 },
  textView: { justifyContent: "center" },
});
